In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

Menghitung nilai invers 


In [2]:
M1 = np.matrix([[2,4,6],[1,2,3],[3,1,9]], dtype=int)
M2 =np.matrix([[1,3,7],[3,2,1],[1,5,2]], dtype=int)
Matrix=[M1,M2]

In [3]:
Matrix

[matrix([[2, 4, 6],
         [1, 2, 3],
         [3, 1, 9]]),
 matrix([[1, 3, 7],
         [3, 2, 1],
         [1, 5, 2]])]

In [4]:
for m in Matrix:
    try:
        inverse = np.linalg.inv(m)
    except np.linalg.LinAlgError:
        print("Not invertible. Skip this one.")
        print(m)
        pass
    else:
        print("invertible, here's the inverse of matrix M{}".format(len(Matrix)))
        print(inverse)


Not invertible. Skip this one.
[[2 4 6]
 [1 2 3]
 [3 1 9]]
invertible, here's the inverse of matrix M2
[[-0.01333333  0.38666667 -0.14666667]
 [-0.06666667 -0.06666667  0.26666667]
 [ 0.17333333 -0.02666667 -0.09333333]]


Membuat model regresi linear dengan Sklearn

In [5]:
y = np.array([10,13, 16, 20, 25, 30, 35, 37, 40, 45])
x1= np.array([2, 6, 8, 9, 11, 13, 15, 19, 21, 24])
x2= np.array([40, 43, 45, 48,50, 55, 57, 60, 62, 67])
X= np.stack((x1, x2), axis=-1)

In [6]:
reg = LinearRegression().fit(X, y)


In [7]:
reg.coef_

array([-0.36157963,  1.63988169])

In [8]:
reg.intercept_

-54.69354554737843

Manual Dengan OLS


In [9]:
X=np.hstack((np.ones((10,1)), X))
beta= np.dot(np.linalg.inv(np.dot(np.transpose(X),X)),
             np.dot(np.transpose(X),y))

In [12]:
beta

array([-54.69354555,  -0.36157963,   1.63988169])